In [18]:
import pandas
import sys
import os

print(os.getcwd())
UP_DIR = os.path.dirname(os.path.realpath(os.getcwd()))
sys.path.append(UP_DIR)

import netsim_scenario
import netsim_topology

the_df = pandas.read_excel("test_topo.xlsx", "Sheet1")
the_df

/home/kscott/Projects/netsim/Test

    Time  Source    Dest  owlt_s  data_rate_bps
0    0.0  node_a  node_b     3.0       100000.0
1    NaN  node_b  node_a     3.0       150000.0
2    NaN     NaN  node_c     4.0        50000.0
3    NaN  node_c  node_b     1.0       100000.0
4   30.0  node_a     NaN     NaN            NaN
5    NaN  node_b     NaN     NaN            NaN
6    NaN  node_c     NaN     NaN            NaN
7   60.0  node_a  node_b     3.0       100000.0
8    NaN  node_b  node_c     2.0       200000.0
9    NaN     NaN  node_a     3.0       150000.0
10   NaN  node_c  node_a     1.0       100000.0

In [21]:
foo = netsim_topology.read_topofile_excel_helper("test_topo.xlsx", "Sheet1")

AttributeError: module 'netsim_topology' has no attribute 'read_topofile_excel_helper'